name: ml4w-wayblue

description: personal use

base-image: ghcr.io/ublue-os/bazzite-nvidia

image-version: 41

modules:
  - from-file: common/sddm-modules.yml
  - from-file: common/common-modules.yml
  - from-file: common/nvidia-modules.yml
  - from-file: common/hyprland-modules.yml
  - from-file: common/final-modules.yml
